package pojo;
// Generated Aug 24, 2019 11:05:33 PM by Hibernate Tools 4.3.1



/**
 * Diem generated by hbm2java
 */
public class Diem  implements java.io.Serializable {


     private DiemId id;
     private String hoTen;
     private Float diemGk;
     private Float diemCk;
     private Float diemKhac;
     private Float diemTong;

    public Diem() {
    }

	
    public Diem(DiemId id) {
        this.id = id;
    }
    public Diem(DiemId id, String hoTen, Float diemGk, Float diemCk, Float diemKhac, Float diemTong) {
       this.id = id;
       this.hoTen = hoTen;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.diemKhac = diemKhac;
       this.diemTong = diemTong;
    }
   
    public DiemId getId() {
        return this.id;
    }
    
    public void setId(DiemId id) {
        this.id = id;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public Float getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(Float diemGk) {
        this.diemGk = diemGk;
    }
    public Float getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(Float diemCk) {
        this.diemCk = diemCk;
    }
    public Float getDiemKhac() {
        return this.diemKhac;
    }
    
    public void setDiemKhac(Float diemKhac) {
        this.diemKhac = diemKhac;
    }
    public Float getDiemTong() {
        return this.diemTong;
    }
    
    public void setDiemTong(Float diemTong) {
        this.diemTong = diemTong;
    }




}


