package pojo;
// Generated Aug 8, 2019 11:08:33 PM by Hibernate Tools 4.3.1



/**
 * Sinhvien generated by hbm2java
 */
public class Sinhvien  implements java.io.Serializable {


     private String mssv;
     private String hoTen;
     private Boolean gioiTinh;
     private String cmnd;
     private String matkhau;
     private String matkhaumacdinh;

    public Sinhvien() {
    }

	
    public Sinhvien(String mssv) {
        this.mssv = mssv;
    }
    public Sinhvien(String mssv, String hoTen, Boolean gioiTinh, String cmnd, String matkhaumacdinh, String matkhau) {
       this.mssv = mssv;
       this.hoTen = hoTen;
       this.gioiTinh = gioiTinh;
       this.matkhaumacdinh = matkhaumacdinh;
       this.matkhau = matkhau;
       this.cmnd = cmnd;
    }
   
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public Boolean getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(Boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    
    public String getMatKhauMacDinh() {
        return this.matkhaumacdinh;
    }
    
    public void setMatKhauMacDinh(String matKhauMacDinh) {
        this.matkhaumacdinh = matKhauMacDinh;
    }
    
    public String getMatKhau() {
        return this.matkhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matkhau = matKhau;
    }




}


