package pojo;
// Generated Aug 24, 2019 11:05:33 PM by Hibernate Tools 4.3.1



/**
 * Taikhoan generated by hbm2java
 */
public class Taikhoan  implements java.io.Serializable {


     private String mssv;
     private String matKhauMacDinh;
     private String matKhau;

    public Taikhoan() {
    }

	
    public Taikhoan(String mssv, String matKhauMacDinh) {
        this.mssv = mssv;
        this.matKhauMacDinh = matKhauMacDinh;
    }
    public Taikhoan(String mssv, String matKhauMacDinh, String matKhau) {
       this.mssv = mssv;
       this.matKhauMacDinh = matKhauMacDinh;
       this.matKhau = matKhau;
    }
   
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getMatKhauMacDinh() {
        return this.matKhauMacDinh;
    }
    
    public void setMatKhauMacDinh(String matKhauMacDinh) {
        this.matKhauMacDinh = matKhauMacDinh;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }




}


