package pojo;
// Generated Aug 16, 2019 11:15:36 PM by Hibernate Tools 4.3.1



/**
 * ThoikhoabieuId generated by hbm2java
 */
public class ThoikhoabieuId  implements java.io.Serializable {


     private String maMonHoc;
     private String lop;

    public ThoikhoabieuId() {
    }

    public ThoikhoabieuId(String maMonHoc, String lop) {
       this.maMonHoc = maMonHoc;
       this.lop = lop;
    }
   
    public String getMaMonHoc() {
        return this.maMonHoc;
    }
    
    public void setMaMonHoc(String maMonHoc) {
        this.maMonHoc = maMonHoc;
    }
    public String getLop() {
        return this.lop;
    }
    
    public void setLop(String lop) {
        this.lop = lop;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ThoikhoabieuId) ) return false;
		 ThoikhoabieuId castOther = ( ThoikhoabieuId ) other; 
         
		 return ( (this.getMaMonHoc()==castOther.getMaMonHoc()) || ( this.getMaMonHoc()!=null && castOther.getMaMonHoc()!=null && this.getMaMonHoc().equals(castOther.getMaMonHoc()) ) )
 && ( (this.getLop()==castOther.getLop()) || ( this.getLop()!=null && castOther.getLop()!=null && this.getLop().equals(castOther.getLop()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMaMonHoc() == null ? 0 : this.getMaMonHoc().hashCode() );
         result = 37 * result + ( getLop() == null ? 0 : this.getLop().hashCode() );
         return result;
   }   


}


