package pojo;
// Generated Aug 22, 2019 11:35:44 PM by Hibernate Tools 4.3.1



/**
 * Thoikhoabieu generated by hbm2java
 */
public class Thoikhoabieu  implements java.io.Serializable {


     private ThoikhoabieuId id;
     private String tenMonHoc;
     private String phongHoc;

    public Thoikhoabieu() {
    }

	
    public Thoikhoabieu(ThoikhoabieuId id) {
        this.id = id;
    }
    public Thoikhoabieu(ThoikhoabieuId id, String tenMonHoc, String phongHoc) {
       this.id = id;
       this.tenMonHoc = tenMonHoc;
       this.phongHoc = phongHoc;
    }
   
    public ThoikhoabieuId getId() {
        return this.id;
    }
    
    public void setId(ThoikhoabieuId id) {
        this.id = id;
    }
    public String getTenMonHoc() {
        return this.tenMonHoc;
    }
    
    public void setTenMonHoc(String tenMonHoc) {
        this.tenMonHoc = tenMonHoc;
    }
    public String getPhongHoc() {
        return this.phongHoc;
    }
    
    public void setPhongHoc(String phongHoc) {
        this.phongHoc = phongHoc;
    }




}


